Convert the spec generator to use templates instead of code modules (#180)
* Rework the test generator to use a template
* Update adding a new exercise: generate a stub template
* convert all exercises to use templates
* fix template bugs
* Add an options to verify-exercises: emit TAP output; early exit for test failures

diff --git a/bin/verify-exercises b/bin/verify-exercises
--- a/bin/verify-exercises
+++ b/bin/verify-exercises
@@ -1,14 +1,22 @@
 #!/usr/bin/env bash
 
-# Synopsis:
-# Verify that each exercise's example/exemplar solution passes the tests.
-# You can either verify all exercises or a single exercise.
+usage() {
+    cat >&2 <<END_USAGE
+Synopsis:
+Verify that each exercise's example/exemplar solution passes the tests.
+You can either verify all exercises or a single exercise.
 
-# Example: verify all exercises
-# bin/verify-exercises
+Usage: $0 [-h] [-t] [-e] [exercise_slug]
 
-# Example: verify single exercise
-# bin/verify-exercises two-fer
+Where:
+    -e = early exit for failed tests (default is test all exercises)
+    -t = use TAP output for busted
+
+Example: verify all exercises: $ bin/verify-exercises
+
+Example: verify single exercise: $ bin/verify-exercises two-fer
+END_USAGE
+}
 
 set -eo pipefail
 
@@ -33,7 +41,7 @@ unskip_tests() {
 }
 
 run_tests() {
-    busted --verbose
+    busted "${busted_opts[@]}"
 }
 
 verify_exercise() {
@@ -69,7 +77,9 @@ verify_exercises() {
     count=0
     for exercise_dir in ./exercises/{concept,practice}/${exercise_slug}/; do
         if [[ -d "${exercise_dir}" ]]; then
-            verify_exercise "${exercise_dir}" || ((++errs))
+            if ! verify_exercise "${exercise_dir}"; then
+                $early_exit && die || ((++errs))
+            fi
             ((++count))
         fi
     done
@@ -85,6 +95,21 @@ required_tool perl
 required_tool busted
 
 cd "$(dirname "$(realpath "$0")")/.."
+
+early_exit=false
+busted_opts=( --verbose )
+while getopts ':hte' opt; do
+    case $opt in
+        h) usage
+           exit ;;
+        t) busted_opts+=( --output=TAP ) ;;
+        e) early_exit=true ;;
+        *) echo "invalid option: -$OPTARG" >&2
+           usage
+           exit 2 ;;
+    esac
+done
+shift $((OPTIND - 1))
 
 exercise_slug="${1:-*}"
 verify_exercises "${exercise_slug}"
